### ISSUE TITLE
Canonical Url not outputting to page

### ISSUE THREAD

**Issue by Mac-B** [xintesa/SeoLite#3]
I downloaded and activated the plugin.

Confirmed that the Keywords and Descriptions were working for Nodes within Croogo.

Yet, the Canonical URL is not coming through like those two. Sorry for the lack of information on my side, I'm new to both Croogo and CakePHP.

Any help is appreciated =]

**Comment by rchavik** [comment]
IIRC, you would need to add `echo $this->Seolite->canonical()` in your theme's layout that is used for page views.

It maybe possible to automate, I'm not sure whether it's a good idea to include this tag for every layout.
